### ISSUE TITLE
R devtools installation hangs on testing for >1 hour

### ISSUE THREAD

**Issue by gregpoore** [TIBHannover/BacDiveR#115]
Hello! I'm super excited about BacDiveR and have been trying to download it using the installation instructions (`devtools::install_github("TIBHannover/BacDiveR")`). Unfortunately, although the package downloads and starts running through checks, it never actually completes and hangs on `testing if installed package can be loaded from temporary location`. To troubleshoot, I've tried reinstalling a newer version of R (4.0.3), using conda environments instead of RStudio, and tried using other github installers, but none of them have worked thus far. Do you have any idea what may be going on and if there's a way to skip the installation tests that cause it to hang?

Code below:
```
> install_github("TIBHannover/BacDiveR")
Downloading GitHub repo TIBHannover/BacDiveR@HEAD
✓  checking for file ‘/private/var/folders/v6/49p8qf9n5hx4nn2lnm826rfc0000gn/T/RtmphNPMT1/remotes17e15228a1f39/TIBHannover-BacDiveR-44a2db7/DESCRIPTION’ ...
─  preparing ‘BacDiveR’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘BacDiveR/figure’
─  building ‘BacDiveR_0.9.1.tar.gz’
   
* installing *source* package ‘BacDiveR’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
```
(Hangs there for at least 1 hour and does not proceed)

**Comment by katrinleinweber** [comment]
Hi @gregpoore 👋 I've been out of that work for over a year now, so I'm not sure whether I can definitely help.

I'm thinking that maybe R v4 (or latest devtools?) might be trying to run all tests during installation? That would fail if the password was missing. Strange, that those errors wouldn't be surfaced, though?!?

Please try swapping steps 3 & 2 of the [install process](https://github.com/TIBHannover/BacDiveR/blob/44a2db7fc06823c22a4660de6e9dd86845b245e2/README.md#installation), so that your BacDive login details are already present. That worked for me on a new computer.

Alternatively, cloning this repo and using RStudio's "Install and Restart" option from within the project should also help ;-)

**Comment by katrinleinweber** [comment]
PS: If swapping steps 3 & 2 helped, would you be interested in sending a Pull Request to update the ReadMe?

@axel-klinger probably knows who's currently working for the DSMZ-TIB collaboration and could ping the responsible colleagues to get the PR(s) merged ;-)

**Comment by gregpoore** [comment]
Hi @katrinleinweber! Sorry for the delay responding, but swapping steps 3 and 2 of the install process seems to have fixed the issue. Thanks so much!

I also proposed a change to the ReadMe file on the installation.

**Comment by katrinleinweber** [comment]
Thank you @gregpoore! Please feel free to create a PR with that update. Same caveat as in https://github.com/TIBHannover/BacDiveR/issues/116#issuecomment-795364775 applies, though ;-) I'm trying to get someone at TIB to give me access to this 1 repo again, or to handle the PRs in my stead.
